### ISSUE TITLE
WaxModel Field extension

### ISSUE THREAD

**Issue by mikenosko** [phpwax/phpwax#22] opened 2009-10-14 12:37 UTC
When you extend a Field for a database table it doesnt created it on execution. You need to use the parent to create and than it works with the extended one.

**Comment by sheldon** [comment] 2009-11-23 13:27
you mean the field doesn't get created when trying to use it? got a bit of sample code to illustrate?

**Comment by charlesmarshall** [comment] 2009-11-30 15:53
will give this a try now

**Comment by charlesmarshall** [comment] 2009-11-30 16:26
yeap.. thats big bug ... if i create a new field type .. say "NewIntegerField" that simply extends IntegerField the column is not created on sync

**Comment by charlesmarshall** [comment] 2009-11-30 16:57
So i remember .... the sync starts on Line 178 - WaxDbAdapter ... currently using WXScripts ... need to replace this.

**Comment by charlesmarshall** [comment] 2009-11-30 17:41
right.. the issue is the listing of data types at the top of waxdbadapter.. as the new field name is not in that list the sql to alter the table is invalid .. so the field is never created .. will rework this ..

**Comment by charlesmarshall** [comment] 2009-12-01 10:49
fixed, checked in and tested .. closing

**Closed as completed by charlesmarshall** 2009-12-01 10:49 UTC
Labels: code bug
